import type { Metadata } from "next";
import "./globals.css";

import { GeistSans } from "geist/font/sans";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Twitter Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased dark",
          GeistSans.className
        )}
      >
        <main className="min-h-screen flex flex-col items-center">
          <article className="flex flex-row max-w-[800px] w-full h-screen">
            <section className="w-80 p-2">
              <Sidebar />
            </section>
            <section className="w-full border-gray-600 border-l-[1px] p-0 border-r-[1px]">
              {children}
            </section>
          </article>
        </main>
      </body>
    </html>
  );
}
